---
services:
  db:
    image: postgres:15
    ports: [5432:5432]
    volumes: [db-data:/var/lib/postgresql/data]
    healthcheck:
      test: [CMD-SHELL, pg_isready -U fastapi-start]
      interval: 2s
      timeout: 5s
      retries: 20
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: fastapi-start
  alembic:
    build:
      context: .
      target: alembic
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: postgresql://fastapi-start:mysecretpassword@db/fastapi-start
  web:
    build:
      context: .
      target: web
    ports: [8000:8000]
    depends_on:
      alembic:
        condition: service_completed_successfully
    environment:
      DB_URL: postgresql://fastapi-start:mysecretpassword@db/fastapi-start
  adminer:
    image: adminer:4
    restart: always
    ports: [8080:8080]
    depends_on:
      db:
        condition: service_healthy
volumes:
  db-data:
