"""create user table

Revision ID: 3d7d807cacfe
Revises:
Create Date: 2023-06-21 17:53:34.227152

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3d7d807cacfe"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
